version: "3.8"
services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=${ADMIN_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
  shopware:
    image: shyim/shopware:${SOFTWARE_VERSION_TAG}
    restart: always
    environment:
      APP_SECRET: 440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      INSTANCE_ID: 10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      APP_URL: https://${DOMAIN}
      MAILER_URL: smtp://172.17.0.1:25/?skip_ssl_verify=true&legacy_ssl=false&smtp_ssl_enabled=false&disable_starttls=true
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_URL: mysql://shopware:${ADMIN_PASSWORD}@mysql:3306/shopware
      SHOPWARE_ES_HOSTS:
      SHOPWARE_ES_ENABLED: 0
      SHOPWARE_ES_INDEXING_ENABLED: 0
      SHOPWARE_ES_INDEX_PREFIX:
      COMPOSER_HOME: /tmp/composer
      SHOPWARE_HTTP_CACHE_ENABLED: 1
      SHOPWARE_HTTP_DEFAULT_TTL: 7200
      INSTALL_LOCALE: en-EN
      BLUE_GREEN_DEPLOYMENT: 0
      INSTALL_ADMIN_USERNAME: ${ADMIN_USERNAME}
      INSTALL_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
    ports:
      - 172.17.0.1:8800:80
    volumes:
      - ./state:/state
      - ./plugins:/var/www/html/custom/plugins
      - ./files:/var/www/html/files
      - ./jwt:/var/www/html/config/jwt
      - ./theme:/var/www/html/public/theme
      - ./media:/var/www/html/public/media
      - ./thumbnail:/var/www/html/public/thumbnail
      - ./bundles:/var/www/html/public/bundles
      - ./sitemap:/var/www/html/public/sitemap
