version: "3"

services:

    shopware:
      # use either tag "latest" or any other version like "6.1.5", ...
      image: dockware/dev:latest
      ports:
         - "172.17.0.1:8800:80"
         - "172.17.0.1:3306:3306"
         - "172.17.0.1:22:22"
         - "172.17.0.1:8888:8888"
         - "172.17.0.1:9999:9999"
      volumes:
         - "./db_volume:/var/lib/mysql"
         - "./shop_volume:/var/www/html"
      environment:
         # default = 0, recommended to be OFF for frontend devs
         - XDEBUG_ENABLED=1
         # default = latest PHP, optional = specific version
         - PHP_VERSION=7.4