version: "3.8"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shopware
      - MYSQL_USER=shopware
      - MYSQL_PASSWORD=shopware
      - INSTALL_ADMIN_USERNAME=${INSTALL_ADMIN_USERNAME}
      - INSTALL_ADMIN_PASSWORD=${INSTALL_ADMIN_PASSWORD}
  shopware:
    image: shyim/shopware:6.2.0
    restart: always
    environment:
      - APP_SECRET=440dec3766de53010c5ccf6231c182acfc90bd25cff82e771245f736fd276518
      - INSTANCE_ID=10612e3916e153dd3447850e944a03fabe89440970295447a30a75b151bd844e
      - APP_URL=https://${DOMAIN}
      - DATABASE_HOST=mysql
      - DATABASE_URL=mysql://shopware:shopware@mysql:3306/shopware
    ports:
      - 172.17.0.1:8800:80